In [171]:
import numpy as np
import copy

In [172]:
class NeuralNetwork:
    def __init__(self,inputSize = None,outputSize = None, hiddenLayers=None, noNodes = None, binaryInput = None, binaryOutput = None):
        if (inputSize or outputSize or hiddenLayers or noNodes or binaryInput or binaryOutput ) is None:
            raise Exception("Please provide all the args inputSize,outputSize, hiddenLayers, noNodes, binaryInput, binaryOutput")
        
        if hiddenLayers < 1:
            raise Exception("Hidden Layers should be greater than equal to 1")
        
        self.inputSize = inputSize
        self.outputSize = outputSize
        self.hiddenLayers = hiddenLayers
        self.noNodes = noNodes
        self.binaryInput = binaryInput
        self.binaryOutput = binaryOutput


        # Initliaze weights and biases and layers and learning rate
        self.ff = []
        self.learningRate = 0.1
        self.weights = []
        self.biases = []
        self.__initializeWeightsAndBiases()



    def __backpropagation(self):
        # Backpropagation
        # Output Layer to Hidden Layer
        # This will compute the error for the last layer
        error = self.binaryOutput - self.ff[-1]
        # This will compute the delta for the last layer
        delta = error * self.ff[-1] * (1 - self.ff[-1])
        # This will compute the weight and bias for the last layer
        self.weights[-1] += self.learningRate * np.dot(self.ff[-2].T,delta)
        self.biases[-1] += self.learningRate * delta

        # Hidden Layer to Hidden Layer
        for i in range(self.hiddenLayers-1,0,-1):
            # This will compute the error for the hidden layer
            error = np.dot(delta,self.weights[i+1].T)
            # This will compute the delta for the hidden layer
            delta = error * self.ff[i] * (1 - self.ff[i])
            # This will compute the weight and bias for the hidden layer
            self.weights[i] += self.learningRate * np.dot(self.ff[i-1].T,delta)
            self.biases[i] += self.learningRate * delta

        # Hidden Layer to Input Layer
        # This will compute the error for the first layer
        error = np.dot(delta,self.weights[1].T)
        # This will compute the delta for the first layer
        delta = error * self.ff[0] * (1 - self.ff[0])
        # This will compute the weight and bias for the first layer
        self.weights[0] += self.learningRate * np.dot(self.binaryInput.T,delta)
        self.biases[0] += self.learningRate * delta

    def train(self,epochs = 100):
        for i in range(epochs):
            for each in self.binaryInput:
                self.ff.append(self.__computeOutput(each))
            self.__backpropagation()
            self.ff = []


    def __forward(self):
        for each in self.binaryInput:
            self.ff.append(self.__computeOutput(each))
        return self.ff


    def __initializeWeightsAndBiases(self):
        # Input Layer to Hidden Layer
        self.weights.append(np.random.randn(self.inputSize,self.noNodes))
        self.biases.append(np.random.randn(self.noNodes,1))

        # Hidden Layer to Hidden Layer
        for i in range(1,self.hiddenLayers):
            self.weights.append(np.random.randn(self.noNodes,self.noNodes))
            self.biases.append(np.random.randn(self.noNodes,1))

        # Hidden Layer to Output Layer
        self.weights.append(np.random.randn(self.noNodes,self.outputSize))
        self.biases.append(np.random.randn(self.outputSize,1))

    def __sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    # Forward Propagation
    def __computeOutput(self,input):
        output = copy.deepcopy(input)
        # This will compute the output to the last layer
        for i in range(self.hiddenLayers+1):
            output = self.__sigmoid(np.dot(output,self.weights[i]) + self.biases[i])
        return output

            

In [173]:
input = np.array(
    [
    [0,0,0],
    [0,1,1],
    [1,0,1],
    [1,1,0],
    ]
)

a = np.array([

    [1,2,3],
    [1,2,3],    
    
    ])
b= np.array([
    
    [1,1],

    
])

print(a)
print(b)
print("\n")
print(np.dot(b,a))
print("\n")
print(1/a)

[[1 2 3]
 [1 2 3]]
[[1 1]]


[[2 4 6]]


[[1.         0.5        0.33333333]
 [1.         0.5        0.33333333]]


In [174]:
input = np.array([
[0,0],
[0,1],
[1,0],
[1,1]
])

output = np.array([
[0],
[1],
[1],
[0]
])
ann = NeuralNetwork(inputSize=2,outputSize=1,hiddenLayers=1,noNodes=3,binaryInput=input,binaryOutput=output)
f = ann.train()


ValueError: operands could not be broadcast together with shapes (4,1) (3,1) 