In [127]:
#ONLY WORKS FOR 1 HIDDEN LAYER
# 1 HIDDEN LAYER = 2 BIAS ONLY


# WHAT THE HELL IS THIS ??? LINEAR ALGEBRA COURSE ????????????
import numpy as np
import copy

# input = np.array([
# [0,0],
# [0,1],
# [1,0],
# [1,1]
# ])

input = np.array([
[0,0],
[0,1],
[1,0],
[1,1]
])

output = np.array([
[0],
[1],
[1],
[0]
])



In [128]:
class NeuralNetwork:
    def __init__(self,inputSize = 2,outputSize = 1, hiddenLayers=None, noNodes = None, binaryInput = None, binaryOutput = None):
        if (inputSize or outputSize or hiddenLayers or noNodes or binaryInput or binaryOutput ) is None:
            raise Exception("Please provide all the args inputSize,outputSize, hiddenLayers, noNodes, binaryInput, binaryOutput")
        
        if hiddenLayers < 1:
            raise Exception("Hidden Layers should be greater than equal to 1")
        
        self.inputSize = inputSize
        self.outputSize = outputSize
        self.hiddenLayers = hiddenLayers
        self.noNodes = noNodes
        self.binaryInput = binaryInput
        self.binaryOutput = binaryOutput


        # Initliaze weights and biases and layers and learning rate
        self.ff = []
        self.learningRate = 0.1
        self.weights = []
        self.biases = []
        self.__initializeWeightsAndBiases()


    def __backpropagation(self,ff,output,input):
        input = np.asarray(input)
        # Backpropagation
        # Output Layer to Hidden Layer
        # This will compute the error for the last layer for all outputs
        error =  (output - ff[-1]) 
        delta = np.dot((np.square(error)),0.5) # Delta = 1/2 * Error^2
        delta = delta[-1][-1]
        print("Delta  = ",delta)

        # This will compute the weight and bias for the last layer
        print("Weights Before = {}".format(np.asarray(self.weights[-1])))
        #print("FF = {}".format(ff[-2]))
        self.weights[-1] += self.learningRate * (np.dot(np.asarray(ff[-2]).T,delta).T)
        self.biases[-1] += self.learningRate * delta
        print("Weights After = {}\n\n\n".format(self.weights[-1][-1]))

        # Hidden Layer to Hidden Layer
        for i in range(self.hiddenLayers-1,0,-1):
            # This will compute the error for the hidden layer
            error = np.dot(delta,self.weights[i+1].T)
            # This will compute the delta for the hidden layer
            delta = error * self.ff[i] * (1 - self.ff[i])
            # This will compute the weight and bias for the hidden layer
            self.weights[i] += self.learningRate * np.dot(self.ff[i-1].T,delta)
            self.biases[i] += self.learningRate * delta


        #### Hidden layer ki nodes ka delta nikalo
        #### Multiply karo unko weights se
        ### Unko weights se multiply karo
        ### Unko biases se add karo
        print("DOING FIRST LAYER IN BACK PROP NOW !")
        print("Weights Before = {}".format(np.asarray(self.weights[0])))
        #print(self.ff[0])
        # Hidden Layer to Input Layer
        # This will compute the error for the first layer
        error = np.dot(delta,self.weights[0].T).T
        print("\n\n\n Error = ",error,"\n\n\n")
        # This will compute the delta for the first layer
        delta = np.dot((np.square(error)),0.5) # Delta = 1/2 * Error^2
        print("\n\n\n Delta = ",delta,"\n\n\n")

        print("\n\n\n input = ",input,"\n\n\n")
        print("\n\n\n Weights = ",self.weights,"\n\n\n")
        print("\n\n\n biases[0] = ",self.biases[0],"\n\n\n")
        # This will compute the weight and bias for the first layer
        print(input.shape)
        self.weights[0][0] +=  (np.dot(input[0],delta[0]))
        self.weights[0][1] +=  (np.dot(input[1],delta[1]))

        print("Weights After = {}\n\n\n".format(self.weights[0]))

        #self.biases[0] = self.biases[0].T
        self.biases[0] += self.learningRate * delta[0].T

        # self.weights[0] += self.learningRate * np.dot(self.binaryInput.T,delta)
        # self.biases[0] += self.learningRate * delta

    def train(self,epochs = 100):
        # print("Before Training")
        # for i,each in enumerate(self.weights):
        #     print("Weights = {}  |  Target = {} | Input = {}".format(each,output[i],input[i]))

        for i in range(epochs):
            self.ff = [] # Reset the feed forward list
            self.forward() # Forward Feed
            for i,each in enumerate(self.ff):
                self.__backpropagation(each,self.binaryOutput[i],self.binaryInput[i]) # Back Propagation
            

        # print("After Training")
        # for i,each in enumerate(self.weights):
        #     print("Weights = {}  |  Target = {} | Input = {}".format(each,output[i],input[i]))

    def forward(self):
        for each in self.binaryInput:
            self.ff.append(self.__computeOutput(each))
        return self.ff


    def __initializeWeightsAndBiases(self):
        # Input Layer to Hidden Layer
        self.weights.append(np.random.randn(self.inputSize,self.noNodes))
        self.biases.append(np.random.randn(1,self.noNodes))

        # Hidden Layer to Hidden Layer
        for i in range(1,self.hiddenLayers):
            self.weights.append(np.random.randn(self.noNodes,self.noNodes))
            self.biases.append(np.random.randn(1,self.noNodes)) # Bias for every hidden layer

        # Hidden Layer to Output Layer
        self.weights.append(np.random.randn(self.outputSize,self.noNodes))
        self.biases.append(np.random.randn(self.outputSize,1)) # Bias for the output layer


    def __sigmoid(self,x):
        return 1/(1+np.exp(-copy.deepcopy(x)))
    
    # Forward Propagation
    def __computeOutput(self,input):
        output = copy.deepcopy(input)
        allOutputs = []
        #print(output,"\n")
        # This will compute the output to the last layer
        for i in range(self.hiddenLayers +1):
            if i == 0:
                output = self.__sigmoid(np.dot(output,self.weights[i]) + self.biases[i])
            else:
                output = self.__sigmoid(np.dot(output,np.transpose(self.weights[i])) + self.biases[i])
            allOutputs.append(output)

            #print("Weight  = ",self.weights[i],"Output = ",output,"\n")

        return allOutputs



ann = NeuralNetwork(hiddenLayers=1,noNodes=3,binaryInput=input,binaryOutput=output)

ann.train(25)
print(ann.weights)


Delta  =  0.34336953602509884
Weights Before = [[ 1.42653489 -0.00657963  0.5338427 ]]
Weights After = [1.43932026 0.01071772 0.54407955]



DOING FIRST LAYER IN BACK PROP NOW !
Weights Before = [[-0.68300559 -1.08070602  0.23086426]
 [-0.66033687  0.02121886 -0.34856707]]



 Error =  [[-0.23452331 -0.37108152  0.07927175]
 [-0.22673956  0.00728591 -0.11968731]] 






 Delta =  [[2.75005919e-02 6.88507491e-02 3.14200551e-03]
 [2.57054147e-02 2.65422376e-05 7.16252627e-03]] 






 input =  [0 0] 






 Weights =  [array([[-0.68300559, -1.08070602,  0.23086426],
       [-0.66033687,  0.02121886, -0.34856707]]), array([[1.43932026, 0.01071772, 0.54407955]])] 






 biases[0] =  [[-0.52214772  0.01501338 -0.85622272]] 



(2,)
Weights After = [[-0.68300559 -1.08070602  0.23086426]
 [-0.66033687  0.02121886 -0.34856707]]



Delta  =  0.02139907450674327
Weights Before = [[1.43932026 0.01071772 0.54407955]]
Weights After = [1.4398223  0.01180706 0.54457306]



DOING FIRST LAYER IN BACK 