In [11]:
# WHAT THE HELL IS THIS ??? LINEAR ALGEBRA COURSE ????????????
import numpy as np
import copy

# input = np.array([
# [0,0],
# [0,1],
# [1,0],
# [1,1]
# ])

input = np.array([
[0,0],
[0,1],
[1,0],
[1,1]
])

output = np.array([
[0],
[1],
[1],
[0]
])



In [109]:
class NeuralNetwork:
    def __init__(self,inputSize = 2,outputSize = 1, hiddenLayers=None, noNodes = None, binaryInput = None, binaryOutput = None):
        if (inputSize or outputSize or hiddenLayers or noNodes or binaryInput or binaryOutput ) is None:
            raise Exception("Please provide all the args inputSize,outputSize, hiddenLayers, noNodes, binaryInput, binaryOutput")
        
        if hiddenLayers < 1:
            raise Exception("Hidden Layers should be greater than equal to 1")
        
        self.inputSize = inputSize
        self.outputSize = outputSize
        self.hiddenLayers = hiddenLayers
        self.noNodes = noNodes
        self.binaryInput = binaryInput
        self.binaryOutput = binaryOutput


        # Initliaze weights and biases and layers and learning rate
        self.ff = []
        self.learningRate = 0.1
        self.weights = []
        self.biases = []
        self.__initializeWeightsAndBiases()


    def __backpropagation(self,ff,output,input):
        # Backpropagation
        # Output Layer to Hidden Layer
        # This will compute the error for the last layer for all outputs
        error =  (output - ff[-1]) 
        delta = np.dot((np.square(error)),0.5) # Delta = 1/2 * Error^2
        delta = delta[-1][-1]
        print("Delta  = ",delta)

        # This will compute the weight and bias for the last layer
        print("Weights Before = {}".format(np.asarray(self.weights[-1])))
        #print("FF = {}".format(ff[-2]))
        self.weights[-1] += self.learningRate * (np.dot(np.asarray(ff[-2]).T,delta).T)
        self.biases[-1] += self.learningRate * delta
        print("Weights After = {}\n\n\n".format(self.weights[-1][-1]))

        # Hidden Layer to Hidden Layer
        for i in range(self.hiddenLayers-1,0,-1):
            # This will compute the error for the hidden layer
            error = np.dot(delta,self.weights[i+1].T)
            # This will compute the delta for the hidden layer
            delta = error * self.ff[i] * (1 - self.ff[i])
            # This will compute the weight and bias for the hidden layer
            self.weights[i] += self.learningRate * np.dot(self.ff[i-1].T,delta)
            self.biases[i] += self.learningRate * delta


        print("Weights Before = {}".format(np.asarray(self.weights[0])))
        #print(self.ff[0])
        # Hidden Layer to Input Layer
        # This will compute the error for the first layer
        error = np.dot(delta,self.weights[0].T).T
        print("\n\n\n",error,"\n\n\n")
        # This will compute the delta for the first layer
        delta = np.dot((np.square(error)),0.5) # Delta = 1/2 * Error^2
        print("\n\n\n",delta,"\n\n\n")

        print("\n\n\n",np.dot(np.asarray(input),delta).T,"\n\n\n")
        # This will compute the weight and bias for the first layer
        self.weights[0][0] += self.learningRate * (np.dot(delta,input[0]))
        self.weights[0][1] += self.learningRate * (np.dot(delta,input[1]))

        print("Weights After = {}\n\n\n".format(self.weights[0]))

        #self.biases[0] = self.biases[0].T
        self.biases[0] += self.learningRate * delta

        # self.weights[0] += self.learningRate * np.dot(self.binaryInput.T,delta)
        # self.biases[0] += self.learningRate * delta

    def train(self,epochs = 100):
        # print("Before Training")
        # for i,each in enumerate(self.weights):
        #     print("Weights = {}  |  Target = {} | Input = {}".format(each,output[i],input[i]))

        for i in range(epochs):
            self.ff = [] # Reset the feed forward list
            self.forward() # Forward Feed
            for i,each in enumerate(self.ff):
                self.__backpropagation(each,self.binaryOutput[i],self.binaryInput[i]) # Back Propagation
            

        # print("After Training")
        # for i,each in enumerate(self.weights):
        #     print("Weights = {}  |  Target = {} | Input = {}".format(each,output[i],input[i]))

    def forward(self):
        for each in self.binaryInput:
            self.ff.append(self.__computeOutput(each))
        return self.ff


    def __initializeWeightsAndBiases(self):
        # Input Layer to Hidden Layer
        self.weights.append(np.random.randn(self.inputSize,self.noNodes))
        self.biases.append(np.random.randn(1,self.noNodes))

        # Hidden Layer to Hidden Layer
        for i in range(1,self.hiddenLayers):
            self.weights.append(np.random.randn(self.noNodes,self.noNodes))
            self.biases.append(np.random.randn(1,self.noNodes)) # Bias for every hidden layer

        # Hidden Layer to Output Layer
        self.weights.append(np.random.randn(self.outputSize,self.noNodes))
        self.biases.append(np.random.randn(self.outputSize,1)) # Bias for the output layer


    def __sigmoid(self,x):
        return 1/(1+np.exp(-copy.deepcopy(x)))
    
    # Forward Propagation
    def __computeOutput(self,input):
        output = copy.deepcopy(input)
        allOutputs = []
        #print(output,"\n")
        # This will compute the output to the last layer
        for i in range(self.hiddenLayers +1):
            if i == 0:
                output = self.__sigmoid(np.dot(output,self.weights[i]) + self.biases[i])
            else:
                output = self.__sigmoid(np.dot(output,np.transpose(self.weights[i])) + self.biases[i])
            allOutputs.append(output)

            #print("Weight  = ",self.weights[i],"Output = ",output,"\n")

        return allOutputs



ann = NeuralNetwork(hiddenLayers=1,noNodes=3,binaryInput=input,binaryOutput=output)

ann.train(1)
print(ann.weights)


Delta  =  0.024879284142895128
Weights Before = [[-0.55654189  0.97148866  0.74742739]]
Weights After = [-0.55481724  0.97270238  0.74947059]



Weights Before = [[-0.52720972  0.90801124  1.37965819]
 [-0.17163992 -1.13252041 -0.76711495]]



 [[-0.0131166   0.02259067  0.03432491]
 [-0.00427028 -0.0281763  -0.01908527]] 






 [[8.60226022e-05 2.55169176e-04 5.89099657e-04]
 [9.11763840e-06 3.96951857e-04 1.82123783e-04]] 






 [0. 0. 0.] 





ValueError: non-broadcastable output operand with shape (3,) doesn't match the broadcast shape (2,3)